@endpoint = https://frq5ywynzb.execute-api.eu-west-1.amazonaws.com/prod

POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location": "London",
    "name": "Best Location"
}
###

GET {{endpoint}}/spaces?spaceId=asdasd
###