@endpoint = https://frq5ywynzb.execute-api.eu-west-1.amazonaws.com/prod

POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location": "London",
    "name": "Best Location"
}
###

PUT {{endpoint}}/spaces?spaceId=590bd5d0-2be9-4966-a7d3-3b24f9f810e0
Content-Type: application/json

{
    "location": "Updated Location",
}
###

GET {{endpoint}}/spaces?spaceId=590bd5d0-2be9-4966-a7d3-3b24f9f810e0
###


GET {{endpoint}}/spaces?location=London
###